# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: upload_image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='upload_image.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12upload_image.proto\"@\n\x0bUploadImage\x12\x14\n\x0c\x63ontent_type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05image\x18\x03 \x01(\x0c\",\n\x0cUploadImages\x12\x1c\n\x06images\x18\x01 \x03(\x0b\x32\x0c.UploadImage\"5\n\x13UploadImageResponse\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2C\n\x12UploadImageManager\x12-\n\x04post\x12\r.UploadImages\x1a\x14.UploadImageResponse\"\x00\x62\x06proto3'
)




_UPLOADIMAGE = _descriptor.Descriptor(
  name='UploadImage',
  full_name='UploadImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content_type', full_name='UploadImage.content_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='UploadImage.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='UploadImage.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=86,
)


_UPLOADIMAGES = _descriptor.Descriptor(
  name='UploadImages',
  full_name='UploadImages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='UploadImages.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=132,
)


_UPLOADIMAGERESPONSE = _descriptor.Descriptor(
  name='UploadImageResponse',
  full_name='UploadImageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='UploadImageResponse.error', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='UploadImageResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=187,
)

_UPLOADIMAGES.fields_by_name['images'].message_type = _UPLOADIMAGE
DESCRIPTOR.message_types_by_name['UploadImage'] = _UPLOADIMAGE
DESCRIPTOR.message_types_by_name['UploadImages'] = _UPLOADIMAGES
DESCRIPTOR.message_types_by_name['UploadImageResponse'] = _UPLOADIMAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UploadImage = _reflection.GeneratedProtocolMessageType('UploadImage', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADIMAGE,
  '__module__' : 'upload_image_pb2'
  # @@protoc_insertion_point(class_scope:UploadImage)
  })
_sym_db.RegisterMessage(UploadImage)

UploadImages = _reflection.GeneratedProtocolMessageType('UploadImages', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADIMAGES,
  '__module__' : 'upload_image_pb2'
  # @@protoc_insertion_point(class_scope:UploadImages)
  })
_sym_db.RegisterMessage(UploadImages)

UploadImageResponse = _reflection.GeneratedProtocolMessageType('UploadImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADIMAGERESPONSE,
  '__module__' : 'upload_image_pb2'
  # @@protoc_insertion_point(class_scope:UploadImageResponse)
  })
_sym_db.RegisterMessage(UploadImageResponse)



_UPLOADIMAGEMANAGER = _descriptor.ServiceDescriptor(
  name='UploadImageManager',
  full_name='UploadImageManager',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=189,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='post',
    full_name='UploadImageManager.post',
    index=0,
    containing_service=None,
    input_type=_UPLOADIMAGES,
    output_type=_UPLOADIMAGERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPLOADIMAGEMANAGER)

DESCRIPTOR.services_by_name['UploadImageManager'] = _UPLOADIMAGEMANAGER

# @@protoc_insertion_point(module_scope)
